import type { ExpansionResult, ExpansionNarsStep, TicTacToeState, ExpansionDefinition } from "../expansion-types.ts";
const goal = (p: string) => `<{SELF} --> [${p}]>! :|:`;
const belief = (p: string) => `<{board} --> [${p}]>. :|:`;
export const definition: ExpansionDefinition = { id: "tictactoe", title: "TicTacToe", subtitle: "复合棋盘与胜负反馈", actions: ["^cell0", "^cell1", "^cell2", "^cell3", "^cell4", "^cell5", "^cell6", "^cell7", "^cell8"], cycles: 10, source: "OpenNARS Lab / TicTacToe.java", url: "https://github.com/opennars/opennars-lab/blob/master/src/main/java/org/opennars/lab/tictactoe/TicTacToe.java", license: "GPL-3.0-or-later", narsPriorRules: ["<(&/,<{board} --> [center_open]>,(^cell4,{SELF})) =/> <{SELF} --> [play]>>."], narsPriorNote: "含预置领域规则与因果假设，不是从空白自主学出。" };
export function create(seed: number): TicTacToeState { return { game: "tictactoe", seed, tick: 0, reward: 0, pendingFeedback: [], board: Array(9).fill(null), turn: "x", winner: null, moves: 0 }; }
function winner(board: TicTacToeState["board"]): "x" | "o" | "draw" | null { for (const [a,b,c] of [[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]] as number[][]) if (board[a] && board[a] === board[b] && board[a] === board[c]) return board[a]; return board.every(Boolean) ? "draw" : null; }
export function buildNarsStep(state: TicTacToeState): ExpansionNarsStep { const occupied = state.board.map((v,i) => v ? belief(`cell${i}_${v}`) : ""); occupied.push(belief(state.board[4] === null ? "center_open" : "center_taken")); return { beliefs: occupied.filter(Boolean), goals: [goal(state.winner === "x" ? "win" : "play")], feedback: state.pendingFeedback.splice(0), cycles: definition.cycles }; }
export function advance(state: TicTacToeState, raw: string | null): ExpansionResult { const action = String(raw ?? "").replace(/^\^/, "").toLowerCase(); const notes: string[] = []; state.reward = 0; const match = action.match(/^cell([0-8])$/); if (match && !state.winner) { const i = Number(match[1]); if (!state.board[i]) { state.board[i] = state.turn; state.moves++; state.winner = winner(state.board); if (state.winner) { state.reward = state.winner === "x" ? 1 : 0; state.pendingFeedback.push(belief(state.winner === "draw" ? "draw" : state.winner === "x" ? "win" : "loss")); notes.push(state.winner.toUpperCase()); } else state.turn = state.turn === "x" ? "o" : "x"; } } state.tick++; return { notes, feedback: state.pendingFeedback.slice(), reward: state.reward }; }
export function applyManualControl(state: TicTacToeState, action: string): boolean { const normalized = action.replace(/^\^/, "").toLowerCase(); if (!/^cell[0-8]$/.test(normalized)) return false; const before = state.moves; advance(state, normalized); return state.moves > before; }
