import { copyFileSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const sourceRoot = resolve(projectRoot, "src");
const publicRoot = resolve(projectRoot, "public");
const outputRoot = resolve(projectRoot, "dist");

const sourceFiles = ["index.html", "styles.css", "app.js", "input-behavior.js"];
const publicFiles = ["nars-worker.js", "build-meta.json"];

rmSync(outputRoot, { recursive: true, force: true });
mkdirSync(outputRoot, { recursive: true });

for (const file of sourceFiles) copyFileSync(resolve(sourceRoot, file), resolve(outputRoot, file));
for (const file of publicFiles) copyFileSync(resolve(publicRoot, file), resolve(outputRoot, file));

const metadata = JSON.parse(readFileSync(resolve(publicRoot, "build-meta.json"), "utf8"));
const deploymentReadme = `# OpenNARS 3.0.4 TypeScript Web Terminal\n\nThis directory is generated by the private \`OpenNARS-304-ts-web-demo\` source project.\n\n- Library version: ${metadata.packageVersion}\n- Core version: ${metadata.coreVersion}\n- Source commit: ${metadata.sourceCommit}\n- Worker built at: ${metadata.builtAt}\n`;
writeFileSync(resolve(outputRoot, "README.md"), deploymentReadme, "utf8");

console.log(JSON.stringify({ ok: true, outputRoot, files: sourceFiles.length + publicFiles.length + 1 }, null, 2));
