import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const metadata = JSON.parse(readFileSync(resolve(projectRoot, "public", "build-meta.json"), "utf8"));
const lines = [
  "# OpenNARS 3.0.4 TypeScript Demo Lab",
  "",
  "[简体中文](#简体中文) | [English](#english)",
  "",
  "## 简体中文",
  "",
  "本目录是 OpenNARS-304-ts-web-demo 生成的静态网站。无需后端服务。",
  "",
  "- 库版本：" + metadata.packageVersion,
  "- 核心版本：" + metadata.coreVersion,
  "- 核心源码提交：" + metadata.sourceCommit,
  "- Worker 构建时间：" + metadata.builtAt,
  "- Demo Lab：https://arcj137442.github.io/opennars-304-ts-lab/",
  "- NARS 终端：terminal.html",
  "- SimNAR Microworld：microworld.html",
  "- 感知运动演示：demo.html?game=pong|alien|bandrobot|cartpole|hunt",
  "",
  "Microworld/Pong 与 NARust-o 环境端口的来源及许可见 COPYING-GPL-3.0.txt 和 COPYING-ONA-MIT.txt。",
  "",
  "## English",
  "",
  "This directory contains the static site generated by OpenNARS-304-ts-web-demo. No backend is required.",
  "",
  "- Package version: " + metadata.packageVersion,
  "- Core version: " + metadata.coreVersion,
  "- Core source commit: " + metadata.sourceCommit,
  "- Worker build time: " + metadata.builtAt,
  "- Demo Lab: https://arcj137442.github.io/opennars-304-ts-lab/",
  "- NARS terminal: terminal.html",
  "- SimNAR Microworld: microworld.html",
  "- Sensorimotor demos: demo.html?game=pong|alien|bandrobot|cartpole|hunt",
  "",
  "See COPYING-GPL-3.0.txt and COPYING-ONA-MIT.txt for upstream attribution and license terms.",
  "",
];
writeFileSync(resolve(projectRoot, "dist", "README.md"), lines.join("\n"), "utf8");
console.log(JSON.stringify({ ok: true, output: resolve(projectRoot, "dist", "README.md") }, null, 2));
