import { createGridWorld, advanceGridWorld, collectGridSensors, type GridAction, type GridTopology, type GridWorld } from "./gridworld/model.ts";
import { drawGridWorld } from "./gridworld/render.ts";
import { RuntimeTelemetryView } from "./ui/runtime-telemetry.ts";
import { mountExperienceTimeline } from "./ui/experience-timeline.ts";
import type { BeliefSnapshot, ExperienceEvent } from "./experience/contract.ts";
import { mountIcons, setIcon } from "./ui/icons.ts";
import { nextWorldStepDeadline } from "./world-clock.ts";
import { MICROWORLD_STARTER_PRIORS } from "./microworld/nars-priors.ts";

type WorkerEvent = { type: string; cyclesPerStep?: number; action?: number; operator?: string | null; actionSource?: string; cycles?: number; narTime?: string; elapsedMs?: number; reasoner?: { concepts: number; conceptCapacity: number; novelTasks: number; sequenceTasks: number; recentOperations: number; narTime: string }; event?: ExperienceEvent; events?: ExperienceEvent[]; beliefs?: BeliefSnapshot[]; stats?: { retained: number; dropped: number }; kind?: string; text?: string; step?: number; message?: string };
type RuntimeMode = "sync" | "async";

function element<T extends Element>(selector: string): T { const found = document.querySelector(selector); if (!found) throw new Error(`Missing Grid Microworld element: ${selector}`); return found as T; }
const ui = {
  canvas: element<HTMLCanvasElement>("#grid-canvas"), runtime: element<HTMLElement>("#grid-runtime"), status: element<HTMLElement>("#grid-status"), topology: element<HTMLSelectElement>("#grid-topology"), topologyMark: element<HTMLElement>("#topology-mark"), cols: element<HTMLInputElement>("#grid-cols"), rows: element<HTMLInputElement>("#grid-rows"), cycles: element<HTMLInputElement>("#grid-cycles"), babble: element<HTMLInputElement>("#grid-babble"), speed: element<HTMLInputElement>("#grid-speed"), speedValue: element<HTMLOutputElement>("#grid-speed-value"), colsValue: element<HTMLOutputElement>("#grid-cols-value"), rowsValue: element<HTMLOutputElement>("#grid-rows-value"), cyclesValue: element<HTMLOutputElement>("#grid-cycles-value"), babbleValue: element<HTMLOutputElement>("#grid-babble-value"), run: element<HTMLButtonElement>("#grid-run"), step: element<HTMLButtonElement>("#grid-step"), reset: element<HTMLButtonElement>("#grid-reset"), operation: element<HTMLElement>("#grid-operation"), source: element<HTMLOutputElement>("#grid-source"), narTime: element<HTMLElement>("#grid-nar-time"), stepCount: element<HTMLOutputElement>("#grid-step-count"), good: element<HTMLElement>("#grid-good"), bad: element<HTMLElement>("#grid-bad"), sensors: element<HTMLElement>("#grid-sensors"), log: element<HTMLOListElement>("#grid-log"), clearLog: element<HTMLButtonElement>("#grid-clear-log"), fps: element<HTMLOutputElement>("#fps-hud"), tps: element<HTMLOutputElement>("#tps-hud"), rps: element<HTMLOutputElement>("#rps-hud"), fpsBar: element<HTMLElement>("#fps-bar"), tpsBar: element<HTMLElement>("#tps-bar"), rpsBar: element<HTMLElement>("#rps-bar"), tpsTarget: element<HTMLOutputElement>("#tps-target"), tpsRatio: element<HTMLOutputElement>("#tps-ratio"), pageMemory: element<HTMLOutputElement>("#page-memory"), concepts: element<HTMLOutputElement>("#concept-count"), taskBags: element<HTMLOutputElement>("#task-bags"), experiencePanel: element<HTMLDetailsElement>("#grid-experience-panel"), experienceList: element<HTMLOListElement>("#grid-experience-list"), experienceStatus: element<HTMLOutputElement>("#grid-experience-status"), experienceMeta: element<HTMLElement>("#grid-experience-meta"), modeInputs: [...document.querySelectorAll<HTMLInputElement>('input[name="grid-mode"]')], manual: [...document.querySelectorAll<HTMLButtonElement>("[data-grid-action]")], };
const telemetry = new RuntimeTelemetryView({ fps: ui.fps, tps: ui.tps, rps: ui.rps, tpsTarget: ui.tpsTarget, tpsRatio: ui.tpsRatio, fpsBar: ui.fpsBar, tpsBar: ui.tpsBar, rpsBar: ui.rpsBar, pageMemory: ui.pageMemory, concepts: ui.concepts, taskBags: ui.taskBags });
const context = ui.canvas.getContext("2d"); if (!context) throw new Error("Grid canvas is unavailable"); const gridContext = context as CanvasRenderingContext2D;
const gridAssets = { agent: new Image(), food: new Image(), fire: new Image() };
gridAssets.agent.src = "./assets/agent.png";
gridAssets.food.src = "./assets/food.png";
gridAssets.fire.src = "./assets/fire.png";
Object.values(gridAssets).forEach((asset) => asset?.addEventListener("load", () => resizeCanvas()));
const experienceTimeline = mountExperienceTimeline({ details: ui.experiencePanel, list: ui.experienceList, status: ui.experienceStatus, meta: ui.experienceMeta }, (open) => { if (state.worker) state.worker.postMessage({ type: "experience-snapshot", open }); });
const topologyMarks: Record<GridTopology, string> = { square: "□", triangle: "△", hexagon: "⬡" };
const sensorLabels = ["G1", "G2", "G3", "B1", "B2", "B3"];
const randomSeed = (): number => globalThis.crypto?.getRandomValues ? globalThis.crypto.getRandomValues(new Uint32Array(1))[0] || 1 : (Date.now() >>> 0) || 1;
const state: { seed: number; world: GridWorld; worker: Worker | null; generation: number; running: boolean; pending: boolean; mode: RuntimeMode; queuedAction: GridAction; speed: number; cycles: number; babble: number; nextStep: number; requestTick: number; lastAction: GridAction; } = { seed: randomSeed(), world: createGridWorld("square", 10, 8, 3040304), worker: null, generation: 0, running: true, pending: false, mode: "sync", queuedAction: 0, speed: 20, cycles: 10, babble: .1, nextStep: 0, requestTick: -1, lastAction: 0 };

function appendLog(text: string): void { const row = document.createElement("li"); row.textContent = `${String(state.world.tick).padStart(5, "0")} ${text}`; ui.log.append(row); while (ui.log.children.length > 120) ui.log.firstElementChild?.remove(); ui.log.scrollTop = ui.log.scrollHeight; }
function renderSensors(): void { ui.sensors.replaceChildren(); state.world.sensors.forEach((value, index) => { const cell = document.createElement("span"); cell.textContent = sensorLabels[index]; cell.classList.toggle("active", value > .1); cell.style.opacity = String(.35 + value * .65); ui.sensors.append(cell); }); }
function renderMetrics(): void { ui.stepCount.value = String(state.world.tick).padStart(6, "0"); ui.stepCount.textContent = ui.stepCount.value; ui.good.textContent = String(state.world.eaten.good); ui.bad.textContent = String(state.world.eaten.bad); ui.topologyMark.textContent = topologyMarks[state.world.topology]; ui.tpsTarget.value = `${state.speed.toFixed(1)} TPS`; ui.tpsTarget.textContent = ui.tpsTarget.value; renderSensors(); }
function resizeCanvas(): void { const rect = ui.canvas.getBoundingClientRect(); const ratio = window.devicePixelRatio || 1; const width = Math.max(1, Math.round(rect.width * ratio)); const height = Math.max(1, Math.round(rect.height * ratio)); if (ui.canvas.width !== width || ui.canvas.height !== height) { ui.canvas.width = width; ui.canvas.height = height; } drawGridWorld(gridContext, state.world, gridAssets); }
function setRuntime(value: "booting" | "ready" | "fault", text: string): void { ui.runtime.dataset.state = value; ui.runtime.textContent = text; }
function applyAction(action: GridAction, source: string): void { const result = advanceGridWorld(state.world, action); state.lastAction = action; if (action !== 0) appendLog(`${source} · ${action === 1 ? "^Right" : action === 2 ? "^Left" : "^Forward"}`); if (result.eaten) appendLog(`${result.eaten === "good" ? "奖励 +1" : "代价 -1"} · ${result.eaten}`); telemetry.environmentTick(performance.now()); renderMetrics(); resizeCanvas(); }
function requestStep(force = false): void { if (!state.worker || state.pending || (!state.running && !force)) return; const sensors = collectGridSensors(state.world); state.pending = true; state.requestTick = state.world.tick; ui.status.textContent = "推理中"; state.worker.postMessage({ type: "step", sensors, reward: state.world.reward, seed: state.seed, cycles: state.cycles, babble: state.babble }); }
function reset(): void { state.seed = randomSeed(); state.world = createGridWorld(ui.topology.value as GridTopology, Number(ui.cols.value), Number(ui.rows.value), state.seed); state.pending = false; state.queuedAction = 0; state.nextStep = performance.now(); state.requestTick = -1; state.running = true; ui.log.replaceChildren(); experienceTimeline.reset(); renderMetrics(); startWorker(); }
function startWorker(): void { state.generation += 1; const generation = state.generation; state.worker?.terminate(); const worker = new Worker("./microworld-worker.js"); state.worker = worker; state.pending = false; setRuntime("booting", "启动推理器"); worker.addEventListener("message", ({ data }: MessageEvent<WorkerEvent>) => { if (generation !== state.generation || !data) return; if (data.type === "booting") return; if (data.type === "ready") { setRuntime("ready", "推理器在线"); experienceTimeline.reset(); appendLog("NARS 已就绪 · 网格感知接入"); requestStep(); return; } if (data.type === "experience-reset") { experienceTimeline.reset(); return; } if (data.type === "experience") { if (data.event) experienceTimeline.add(data.event); return; } if (data.type === "experience-snapshot") { for (const event of data.events ?? []) experienceTimeline.add(event); if (data.stats) ui.experienceMeta.textContent = `窗口 ${data.stats.retained + data.stats.dropped} · 保留 ${data.stats.retained} · 丢弃 ${data.stats.dropped}`; experienceTimeline.setBeliefs(data.beliefs ?? []); return; } if (data.type === "operation") { ui.operation.textContent = `${data.operator ?? "?"}({SELF})`; ui.source.value = "NARS"; appendLog(`NARS · ${data.operator ?? "?"}`); return; } if (data.type === "step-complete") { state.pending = false; ui.narTime.textContent = `NAR ${data.narTime ?? "0"}`; ui.operation.textContent = data.operator ? `${data.operator}({SELF})` : "本步未发出操作"; ui.source.value = (data.actionSource ?? "idle").toUpperCase(); telemetry.inference(Number(data.cycles ?? state.cycles)); telemetry.updateReasoner(data.reasoner); if (state.mode === "sync") { applyAction((data.action ?? 0) as GridAction, data.actionSource === "babble" ? "Babble" : data.operator ? "NARS" : "空闲"); state.nextStep = nextWorldStepDeadline(state.nextStep, performance.now(), state.speed); } else if (data.action) state.queuedAction = (data.action ?? 0) as GridAction; ui.status.textContent = state.running ? "运行中" : "已暂停"; return; } if (data.type === "fault") { state.running = false; state.pending = false; setRuntime("fault", "推理异常"); appendLog(data.message ?? "Worker 异常"); } }); worker.addEventListener("error", () => { if (generation !== state.generation) return; state.running = false; state.pending = false; setRuntime("fault", "Worker 异常"); }); worker.postMessage({ type: "reset", seed: state.seed, priorRules: MICROWORLD_STARTER_PRIORS }); }
function setMode(mode: RuntimeMode): void { state.mode = mode; appendLog(`节奏 · ${mode === "sync" ? "同步" : "异步"}`); }
function updateControls(): void { ui.speedValue.value = `${state.speed} TPS`; ui.speedValue.textContent = ui.speedValue.value; ui.colsValue.value = ui.cols.value; ui.colsValue.textContent = ui.cols.value; ui.rowsValue.value = ui.rows.value; ui.rowsValue.textContent = ui.rows.value; ui.cyclesValue.value = ui.cycles.value; ui.cyclesValue.textContent = ui.cycles.value; ui.babbleValue.value = `${ui.babble.value}%`; ui.babbleValue.textContent = ui.babbleValue.value; state.speed = Number(ui.speed.value); state.cycles = Number(ui.cycles.value); state.babble = Number(ui.babble.value) / 100; telemetry.setTargetTps(state.speed); telemetry.setCyclesPerTick(state.cycles); }
function frame(now: number): void { telemetry.frame(now); if (state.running && state.mode === "async" && now >= state.nextStep) { applyAction(state.queuedAction, "异步"); state.queuedAction = 0; state.nextStep = now + 1000 / state.speed; } if (state.running && state.worker && !state.pending && (state.mode === "async" ? state.world.tick > state.requestTick : now >= state.nextStep)) requestStep(); resizeCanvas(); requestAnimationFrame(frame); }

mountIcons(); updateControls(); renderMetrics(); startWorker();
ui.run.addEventListener("click", () => { state.running = !state.running; setIcon(ui.run, state.running ? "pause" : "play"); ui.status.textContent = state.running ? "运行中" : "已暂停"; if (state.running) state.nextStep = performance.now(); });
ui.step.addEventListener("click", () => { state.running = false; requestStep(true); });
ui.reset.addEventListener("click", reset);
ui.topology.addEventListener("change", reset); ui.cols.addEventListener("input", updateControls); ui.rows.addEventListener("input", updateControls); ui.cycles.addEventListener("input", updateControls); ui.babble.addEventListener("input", updateControls); ui.speed.addEventListener("input", updateControls);
ui.modeInputs.forEach((input) => input.addEventListener("change", () => setMode(input.value as RuntimeMode)));
ui.manual.forEach((button) => button.addEventListener("click", () => applyAction(Number(button.dataset.gridAction) as GridAction, "手动")));
ui.clearLog.addEventListener("click", () => ui.log.replaceChildren());
window.addEventListener("resize", resizeCanvas); window.addEventListener("pagehide", () => { state.worker?.terminate(); telemetry.dispose(); experienceTimeline.dispose(); }, { once: true });
requestAnimationFrame(frame);
