import { createGridWorld, advanceGridWorld, collectGridSensors, moveGridObject, type GridAction, type GridTopology, type GridWorld } from "./gridworld/model.ts";
import { drawGridWorld, gridCellAtPoint } from "./gridworld/render.ts";
import { RuntimeTelemetryView } from "./ui/runtime-telemetry.ts";
import { mountExperienceTimeline } from "./ui/experience-timeline.ts";
import type { BeliefSnapshot, ExperienceEvent } from "./experience/contract.ts";
import { mountIcons, setIcon } from "./ui/icons.ts";
import { nextWorldStepDeadline } from "./world-clock.ts";
import { MICROWORLD_STARTER_PRIORS } from "./microworld/nars-priors.ts";
import { renderReasonerObservatory } from "./ui/reasoner-observatory.ts";

type WorkerEvent = { type: string; cyclesPerStep?: number; action?: number; operator?: string | null; actionSource?: string; cycles?: number; narTime?: string; elapsedMs?: number; reasoner?: { concepts: number; conceptCapacity: number; novelTasks: number; sequenceTasks: number; recentOperations: number; narTime: string }; event?: ExperienceEvent; events?: ExperienceEvent[]; beliefs?: BeliefSnapshot[]; stats?: { retained: number; dropped: number }; kind?: string; text?: string; step?: number; message?: string };
type RuntimeMode = "sync" | "async";

function element<T extends Element>(selector: string): T { const found = document.querySelector(selector); if (!found) throw new Error(`Missing Grid Microworld element: ${selector}`); return found as T; }
function ensureGridObservatoryFields(): void {
  const operation = document.querySelector("#grid-operation");
  if (operation && !document.querySelector("#grid-operation-detail")) { const detail = document.createElement("small"); detail.id = "grid-operation-detail"; detail.className = "nars-panel-detail"; detail.textContent = "每个环境步运行 10 个推理周期"; operation.after(detail); }
  const rewardCard = document.querySelector(".reward-panel");
  if (rewardCard && !document.querySelector("#grid-reward-state")) { const output = document.createElement("output"); output.id = "grid-reward-state"; output.textContent = "尚无反馈"; rewardCard.querySelector(".nars-panel-head")?.append(output); }
  const perceptionCard = document.querySelector(".perception-panel");
  if (perceptionCard && !document.querySelector("#grid-sensor-focus")) { const output = document.createElement("output"); output.id = "grid-sensor-focus"; output.textContent = "暂无目标"; perceptionCard.querySelector(".nars-panel-head")?.append(output); }
  const worldMetrics = document.querySelector(".reward-panel .grid-world-metrics");
  if (worldMetrics && !document.querySelector("#grid-food-ratio")) { const span = document.createElement("span"); span.textContent = "好 / 坏比 "; const strong = document.createElement("strong"); strong.id = "grid-food-ratio"; strong.textContent = "1.00"; span.append(strong); worldMetrics.append(span); const track = document.createElement("div"); track.className = "ratio-track"; const fill = document.createElement("span"); fill.id = "grid-ratio-fill"; track.append(fill); worldMetrics.after(track); }
}
ensureGridObservatoryFields();
const ui = {
  canvas: element<HTMLCanvasElement>("#grid-canvas"), runtime: element<HTMLElement>("#grid-runtime"), status: element<HTMLElement>("#grid-status"), topology: element<HTMLSelectElement>("#grid-topology"), topologyMark: element<HTMLElement>("#topology-mark"), cols: element<HTMLInputElement>("#grid-cols"), rows: element<HTMLInputElement>("#grid-rows"), cycles: element<HTMLInputElement>("#grid-cycles"), babble: element<HTMLInputElement>("#grid-babble"), speed: element<HTMLInputElement>("#grid-speed"), speedValue: element<HTMLOutputElement>("#grid-speed-value"), colsValue: element<HTMLOutputElement>("#grid-cols-value"), rowsValue: element<HTMLOutputElement>("#grid-rows-value"), cyclesValue: element<HTMLOutputElement>("#grid-cycles-value"), babbleValue: element<HTMLOutputElement>("#grid-babble-value"), run: element<HTMLButtonElement>("#grid-run"), step: element<HTMLButtonElement>("#grid-step"), reset: element<HTMLButtonElement>("#grid-reset"), operation: element<HTMLElement>("#grid-operation"), source: element<HTMLOutputElement>("#grid-source"), narTime: element<HTMLElement>("#grid-nar-time"), operationDetail: element<HTMLElement>("#grid-operation-detail"), stepCount: element<HTMLOutputElement>("#grid-step-count"), rewardState: element<HTMLOutputElement>("#grid-reward-state"), foodRatio: element<HTMLElement>("#grid-food-ratio"), ratioFill: element<HTMLElement>("#grid-ratio-fill"), sensorFocus: element<HTMLOutputElement>("#grid-sensor-focus"), good: element<HTMLElement>("#grid-good"), bad: element<HTMLElement>("#grid-bad"), sensors: element<HTMLElement>("#grid-sensors"), log: element<HTMLOListElement>("#grid-log"), clearLog: element<HTMLButtonElement>("#grid-clear-log"), fps: element<HTMLOutputElement>("#fps-hud"), tps: element<HTMLOutputElement>("#tps-hud"), rps: element<HTMLOutputElement>("#rps-hud"), fpsBar: element<HTMLElement>("#fps-bar"), tpsBar: element<HTMLElement>("#tps-bar"), rpsBar: element<HTMLElement>("#rps-bar"), tpsTarget: element<HTMLOutputElement>("#tps-target"), tpsRatio: element<HTMLOutputElement>("#tps-ratio"), pageMemory: element<HTMLOutputElement>("#page-memory"), concepts: element<HTMLOutputElement>("#concept-count"), taskBags: element<HTMLOutputElement>("#task-bags"), experiencePanel: element<HTMLDetailsElement>("#grid-experience-panel"), experienceList: element<HTMLOListElement>("#grid-experience-list"), experienceStatus: element<HTMLOutputElement>("#grid-experience-status"), experienceMeta: element<HTMLElement>("#grid-experience-meta"), modeInputs: [...document.querySelectorAll<HTMLInputElement>('input[name="grid-mode"]')], manual: [...document.querySelectorAll<HTMLButtonElement>("[data-grid-action]")], };
const telemetry = new RuntimeTelemetryView({ fps: ui.fps, tps: ui.tps, rps: ui.rps, tpsTarget: ui.tpsTarget, tpsRatio: ui.tpsRatio, fpsBar: ui.fpsBar, tpsBar: ui.tpsBar, rpsBar: ui.rpsBar, pageMemory: ui.pageMemory, concepts: ui.concepts, taskBags: ui.taskBags });
const context = ui.canvas.getContext("2d"); if (!context) throw new Error("Grid canvas is unavailable"); const gridContext = context as CanvasRenderingContext2D;
const gridAssets = { agent: new Image(), food: new Image(), fire: new Image() };
gridAssets.agent.src = "./assets/agent.png";
gridAssets.food.src = "./assets/food.png";
gridAssets.fire.src = "./assets/fire.png";
Object.values(gridAssets).forEach((asset) => asset?.addEventListener("load", () => resizeCanvas(true)));
const experienceTimeline = mountExperienceTimeline({ details: ui.experiencePanel, list: ui.experienceList, status: ui.experienceStatus, meta: ui.experienceMeta }, (open) => { if (state.worker) state.worker.postMessage({ type: "experience-snapshot", open }); });
const topologyMarks: Record<GridTopology, string> = { square: "□", triangle: "△", hexagon: "⬡" };
const sensorLabels = ["G1", "G2", "G3", "B1", "B2", "B3"];
const randomSeed = (): number => globalThis.crypto?.getRandomValues ? globalThis.crypto.getRandomValues(new Uint32Array(1))[0] || 1 : (Date.now() >>> 0) || 1;
const state: { seed: number; world: GridWorld; worker: Worker | null; generation: number; running: boolean; pending: boolean; mode: RuntimeMode; queuedAction: GridAction; speed: number; cycles: number; babble: number; nextStep: number; requestTick: number; lastAction: GridAction; dragObjectId: string | null; operation: string; operationSource: string; operationStep: number | null; operationNarTime: string; } = { seed: randomSeed(), world: createGridWorld("square", 10, 8, 3040304), worker: null, generation: 0, running: true, pending: false, mode: "sync", queuedAction: 0, speed: 20, cycles: 10, babble: .1, nextStep: 0, requestTick: -1, lastAction: 0, dragObjectId: null, operation: "等待第一步", operationSource: "WAITING", operationStep: null, operationNarTime: "0" };

function canvasPoint(event: PointerEvent): { x: number; y: number } { const rect = ui.canvas.getBoundingClientRect(); return { x: (event.clientX - rect.left) * ui.canvas.width / rect.width, y: (event.clientY - rect.top) * ui.canvas.height / rect.height }; }
function nearestObjectId(cell: GridWorld["agent"]["cell"]): string | null { if (state.world.agent.cell.col === cell.col && state.world.agent.cell.row === cell.row && state.world.agent.cell.face === cell.face) return "agent"; return state.world.foods.find((food) => food.cell.col === cell.col && food.cell.row === cell.row && food.cell.face === cell.face)?.id ?? null; }
function handlePointerDown(event: PointerEvent): void { if (event.button !== 0) return; const point = canvasPoint(event); const cell = gridCellAtPoint(state.world, ui.canvas.width, ui.canvas.height, point.x, point.y); state.dragObjectId = nearestObjectId(cell); if (state.dragObjectId) { ui.canvas.setPointerCapture(event.pointerId); ui.canvas.classList.add("dragging-object"); event.preventDefault(); } }
function handlePointerMove(event: PointerEvent): void { if (!state.dragObjectId) return; const point = canvasPoint(event); const cell = gridCellAtPoint(state.world, ui.canvas.width, ui.canvas.height, point.x, point.y); moveGridObject(state.world, state.dragObjectId, cell); canvasDirty = true; renderMetrics(); resizeCanvas(true); event.preventDefault(); }
function handlePointerEnd(event: PointerEvent): void { if (ui.canvas.hasPointerCapture(event.pointerId)) ui.canvas.releasePointerCapture(event.pointerId); state.dragObjectId = null; ui.canvas.classList.remove("dragging-object"); }

function appendLog(text: string): void { const row = document.createElement("li"); row.textContent = `${String(state.world.tick).padStart(5, "0")} ${text}`; ui.log.append(row); while (ui.log.children.length > 120) ui.log.firstElementChild?.remove(); ui.log.scrollTop = ui.log.scrollHeight; }
function renderSensors(): void { ui.sensors.replaceChildren(); state.world.sensors.forEach((value, index) => { const cell = document.createElement("span"); cell.textContent = sensorLabels[index]; cell.classList.toggle("active", value > .1); cell.style.opacity = String(.35 + value * .65); ui.sensors.append(cell); }); }
function renderMetrics(): void { ui.topologyMark.textContent = topologyMarks[state.world.topology]; ui.tpsTarget.value = `${state.speed.toFixed(1)} TPS`; ui.tpsTarget.textContent = ui.tpsTarget.value; const operationDetail = state.operationStep === null ? `每个环境步运行 ${state.cycles} 个推理周期` : state.operationStep === state.world.tick ? `本步 · NAR 时钟 ${state.operationNarTime}` : `上次操作 · ${state.world.tick - state.operationStep} 步前 · NAR ${state.operationNarTime}`; renderReasonerObservatory({ operation: ui.operation, source: ui.source, detail: ui.operationDetail, narTime: ui.narTime, sensorGrid: ui.sensors, sensorFocus: ui.sensorFocus, rewardState: ui.rewardState, goodCount: ui.good, badCount: ui.bad, foodRatio: ui.foodRatio, ratioFill: ui.ratioFill, stepCount: ui.stepCount }, { operation: state.operation, source: state.operationSource, detail: operationDetail, narTime: state.operationNarTime, sensors: state.world.sensors, rewardType: state.world.reward > 0 ? "good" : state.world.reward < 0 ? "bad" : null, good: state.world.eaten.good + 1, bad: state.world.eaten.bad + 1, step: state.world.tick }); }
let restoringOperation = false;
const operationAuthority = new MutationObserver(() => {
  if (restoringOperation) return;
  const source = ui.source.textContent?.trim().toUpperCase() ?? "WAITING";
  const operation = ui.operation.textContent?.trim() ?? "";
  if ((source === "NARS" || source === "BABBLE") && operation.length > 0) {
    state.operation = operation;
    state.operationSource = source;
    state.operationStep = state.world.tick;
    state.operationNarTime = ui.narTime.textContent?.replace(/^NAR\s*/, "") || state.operationNarTime;
  } else if (source === "IDLE" && state.operationStep !== null) {
    restoringOperation = true;
    renderMetrics();
    restoringOperation = false;
  }
});
operationAuthority.observe(ui.operation, { childList: true, characterData: true, subtree: true });
operationAuthority.observe(ui.source, { childList: true, characterData: true, subtree: true });
let canvasDirty = true;
function resizeCanvas(force = false): void { const rect = ui.canvas.getBoundingClientRect(); const ratio = window.devicePixelRatio || 1; const width = Math.max(1, Math.round(rect.width * ratio)); const height = Math.max(1, Math.round(rect.height * ratio)); const resized = ui.canvas.width !== width || ui.canvas.height !== height; if (resized) { ui.canvas.width = width; ui.canvas.height = height; } if (force || resized || canvasDirty) { drawGridWorld(gridContext, state.world, gridAssets); canvasDirty = false; } }
function setRuntime(value: "booting" | "ready" | "fault", text: string): void { ui.runtime.dataset.state = value; ui.runtime.textContent = text; }
function applyAction(action: GridAction, source: string): void { const result = advanceGridWorld(state.world, action); state.lastAction = action; if (action !== 0) appendLog(`${source} · ${action === 1 ? "^Right" : action === 2 ? "^Left" : "^Forward"}`); if (result.eaten) appendLog(`${result.eaten === "good" ? "奖励 +1" : "代价 -1"} · ${result.eaten}`); telemetry.environmentTick(performance.now()); renderMetrics(); canvasDirty = true; resizeCanvas(true); }
function requestStep(force = false): void { if (!state.worker || state.pending || (!state.running && !force)) return; const sensors = collectGridSensors(state.world); state.pending = true; state.requestTick = state.world.tick; ui.status.textContent = "推理中"; state.worker.postMessage({ type: "step", sensors, reward: state.world.reward, seed: state.seed, cycles: state.cycles, babble: state.babble }); }
function reset(): void { state.seed = randomSeed(); state.world = createGridWorld(ui.topology.value as GridTopology, Number(ui.cols.value), Number(ui.rows.value), state.seed); state.pending = false; state.queuedAction = 0; state.nextStep = performance.now(); state.requestTick = -1; state.running = true; ui.log.replaceChildren(); experienceTimeline.reset(); renderMetrics(); canvasDirty = true; resizeCanvas(true); startWorker(); }
function startWorker(): void { state.generation += 1; const generation = state.generation; state.worker?.terminate(); const worker = new Worker("./microworld-worker.js"); state.worker = worker; state.pending = false; setRuntime("booting", "启动推理器"); worker.addEventListener("message", ({ data }: MessageEvent<WorkerEvent>) => { if (generation !== state.generation || !data) return; if (data.type === "booting") return; if (data.type === "ready") { setRuntime("ready", "推理器在线"); experienceTimeline.reset(); appendLog("NARS 已就绪 · 网格感知接入"); requestStep(); return; } if (data.type === "experience-reset") { experienceTimeline.reset(); return; } if (data.type === "experience") { if (data.event) experienceTimeline.add(data.event); return; } if (data.type === "experience-snapshot") { for (const event of data.events ?? []) experienceTimeline.add(event); if (data.stats) ui.experienceMeta.textContent = `窗口 ${data.stats.retained + data.stats.dropped} · 保留 ${data.stats.retained} · 丢弃 ${data.stats.dropped}`; experienceTimeline.setBeliefs(data.beliefs ?? []); return; } if (data.type === "operation") { ui.operation.textContent = `${data.operator ?? "?"}({SELF})`; ui.source.value = "NARS"; ui.operationDetail.textContent = `NARS 操作 · ${state.world.tick} 步`; appendLog(`NARS · ${data.operator ?? "?"}`); renderMetrics(); return; } if (data.type === "step-complete") { state.pending = false; ui.narTime.textContent = `NAR ${data.narTime ?? "0"}`; ui.operation.textContent = data.operator ? `${data.operator}({SELF})` : "本步未发出操作"; ui.source.value = (data.actionSource ?? "idle").toUpperCase(); ui.operationDetail.textContent = `当前步骤 ${state.world.tick} · ${Number(data.cycles ?? state.cycles)} cycles`; telemetry.inference(Number(data.cycles ?? state.cycles)); telemetry.updateReasoner(data.reasoner); if (state.mode === "sync") { applyAction((data.action ?? 0) as GridAction, data.actionSource === "babble" ? "Babble" : data.operator ? "NARS" : "空闲"); state.nextStep = nextWorldStepDeadline(state.nextStep, performance.now(), state.speed); } else if (data.action) state.queuedAction = (data.action ?? 0) as GridAction; ui.status.textContent = state.running ? "运行中" : "已暂停"; renderMetrics(); return; } if (data.type === "fault") { state.running = false; state.pending = false; setRuntime("fault", "推理异常"); appendLog(data.message ?? "Worker 异常"); } }); worker.addEventListener("error", () => { if (generation !== state.generation) return; state.running = false; state.pending = false; setRuntime("fault", "Worker 异常"); }); worker.postMessage({ type: "reset", seed: state.seed, priorRules: MICROWORLD_STARTER_PRIORS }); }
function setMode(mode: RuntimeMode): void { state.mode = mode; appendLog(`节奏 · ${mode === "sync" ? "同步" : "异步"}`); }
function updateControls(): void { ui.speedValue.value = `${state.speed} TPS`; ui.speedValue.textContent = ui.speedValue.value; ui.colsValue.value = ui.cols.value; ui.colsValue.textContent = ui.cols.value; ui.rowsValue.value = ui.rows.value; ui.rowsValue.textContent = ui.rows.value; ui.cyclesValue.value = ui.cycles.value; ui.cyclesValue.textContent = ui.cycles.value; ui.babbleValue.value = `${ui.babble.value}%`; ui.babbleValue.textContent = ui.babbleValue.value; state.speed = Number(ui.speed.value); state.cycles = Number(ui.cycles.value); state.babble = Number(ui.babble.value) / 100; telemetry.setTargetTps(state.speed); telemetry.setCyclesPerTick(state.cycles); }
function frame(now: number): void { telemetry.frame(now); if (state.running && state.mode === "async" && now >= state.nextStep) { applyAction(state.queuedAction, "异步"); state.queuedAction = 0; state.nextStep = now + 1000 / state.speed; } if (state.running && state.worker && !state.pending && (state.mode === "async" ? state.world.tick > state.requestTick : now >= state.nextStep)) requestStep(); resizeCanvas(); requestAnimationFrame(frame); }

mountIcons(); updateControls(); renderMetrics(); startWorker();
ui.run.addEventListener("click", () => { state.running = !state.running; setIcon(ui.run, state.running ? "pause" : "play"); ui.status.textContent = state.running ? "运行中" : "已暂停"; if (state.running) state.nextStep = performance.now(); });
ui.step.addEventListener("click", () => { state.running = false; requestStep(true); });
ui.reset.addEventListener("click", reset);
ui.topology.addEventListener("change", reset); ui.cols.addEventListener("input", updateControls); ui.rows.addEventListener("input", updateControls); ui.cycles.addEventListener("input", updateControls); ui.babble.addEventListener("input", updateControls); ui.speed.addEventListener("input", updateControls);
ui.modeInputs.forEach((input) => input.addEventListener("change", () => setMode(input.value as RuntimeMode)));
ui.manual.forEach((button) => button.addEventListener("click", () => applyAction(Number(button.dataset.gridAction) as GridAction, "手动")));
ui.clearLog.addEventListener("click", () => ui.log.replaceChildren());
ui.canvas.addEventListener("pointerdown", handlePointerDown);
ui.canvas.addEventListener("pointermove", handlePointerMove);
ui.canvas.addEventListener("pointerup", handlePointerEnd);
ui.canvas.addEventListener("pointercancel", handlePointerEnd);
ui.canvas.addEventListener("contextmenu", (event) => event.preventDefault());
window.addEventListener("resize", () => resizeCanvas(true)); window.addEventListener("pagehide", () => { state.worker?.terminate(); telemetry.dispose(); experienceTimeline.dispose(); }, { once: true });
requestAnimationFrame(frame);
