import { createGame, buildNarsInput, move, type Direction, type Game2048 } from "./games/nars2048.ts";
import { mountIcons, setIcon } from "./ui/icons.ts";
import { mountExperienceTimeline } from "./ui/experience-timeline.ts";
import { RuntimeTelemetryView } from "./ui/runtime-telemetry.ts";
import { Nars2048Renderer } from "./nars2048-renderer.ts";

const el = <T extends Element>(selector: string): T => document.querySelector(selector) as T;
const ui = { board: el<HTMLCanvasElement>("#board"), runtime: el<HTMLElement>("#n2048-runtime"), score: el<HTMLElement>("#score"), highest: el<HTMLElement>("#highest"), round: el<HTMLOutputElement>("#round"), roundCount: el<HTMLElement>("#round-count"), source: el<HTMLOutputElement>("#source"), narTime: el<HTMLOutputElement>("#nar-time"), sensors: el<HTMLElement>("#sensor-list"), last: el<HTMLElement>("#last-event"), log: el<HTMLOListElement>("#log"), run: el<HTMLButtonElement>("#run"), resetBoard: el<HTMLButtonElement>("#reset-board"), resetMemory: el<HTMLButtonElement>("#reset-memory"), toggleMotion: el<HTMLButtonElement>("#toggle-motion"), toggleParticles: el<HTMLButtonElement>("#toggle-particles"), exportLog: el<HTMLButtonElement>("#export-log"), clearLog: el<HTMLButtonElement>("#clear-log"), experiencePanel: el<HTMLDetailsElement>("#n2048-experience"), experienceList: el<HTMLOListElement>("#experience-list"), experienceStatus: el<HTMLOutputElement>("#experience-status"), experienceMeta: el<HTMLElement>("#experience-meta"), fps: el<HTMLOutputElement>("#fps-hud"), tps: el<HTMLOutputElement>("#tps-hud"), rps: el<HTMLOutputElement>("#rps-hud"), fpsBar: el<HTMLElement>("#fps-bar"), tpsBar: el<HTMLElement>("#tps-bar"), rpsBar: el<HTMLElement>("#rps-bar"), tpsTarget: el<HTMLOutputElement>("#tps-target"), tpsRatio: el<HTMLOutputElement>("#tps-ratio"), pageMemory: el<HTMLOutputElement>("#page-memory"), concepts: el<HTMLOutputElement>("#concept-count"), taskBags: el<HTMLOutputElement>("#task-bags") };
const timeline = mountExperienceTimeline({ details: ui.experiencePanel, list: ui.experienceList, status: ui.experienceStatus, meta: ui.experienceMeta }, (open) => worker?.postMessage({ type: "experience-snapshot", open }));
const renderer = new Nars2048Renderer(ui.board);
const telemetry = new RuntimeTelemetryView({ fps: ui.fps, tps: ui.tps, rps: ui.rps, tpsTarget: ui.tpsTarget, tpsRatio: ui.tpsRatio, fpsBar: ui.fpsBar, tpsBar: ui.tpsBar, rpsBar: ui.rpsBar, pageMemory: ui.pageMemory, concepts: ui.concepts, taskBags: ui.taskBags }); telemetry.setTargetTps(8); telemetry.setCyclesPerTick(10);
let game: Game2048 = createGame(2048), worker: Worker | null = null, running = true, pending = false, ready = false, generation = 0, nextStep = 0;
const log = (text: string): void => { const item = document.createElement("li"); item.textContent = text; ui.log.append(item); while (ui.log.children.length > 120) ui.log.firstElementChild?.remove(); ui.log.scrollTop = ui.log.scrollHeight; };
function render(): void { renderer.resize(); renderer.sync(game.board); ui.score.textContent = String(game.score); ui.highest.textContent = String(game.highest); ui.round.textContent = `ROUND ${String(game.round).padStart(2, "0")}`; ui.roundCount.textContent = String(game.round); ui.last.textContent = game.lastEvent; const input = buildNarsInput(game); ui.sensors.replaceChildren(...input.beliefs.map((belief) => { const i = document.createElement("i"); i.textContent = belief.match(/\[(.*?)\]/)?.[1] ?? "state"; return i; })); }
function pulseBoard(kind: "merge" | "slide" | "invalid" | "gameover", direction?: Direction, gained = 0): void { if (direction) renderer.trigger(direction, kind === "merge", gained); if (kind === "invalid" && direction) renderer.invalid(direction); }
function applyMove(direction: Direction, source: string): void { const result = move(game, direction); if (!result.changed) { pulseBoard("invalid", direction); log(`${source} · ^${direction} · 无效移动`); return; } telemetry.environmentTick(performance.now()); pulseBoard(result.gameOver ? "gameover" : result.merged > 0 ? "merge" : "slide", direction, result.gained); log(`${source} · ^${direction} · ${result.merged ? `合并 ${result.merged} 次 · +${result.gained}` : "移动"}`); render(); if (result.gameOver) { game = createGame(game.seed + game.round); game.round += 1; render(); log(`终局 · 自动重开 ROUND ${game.round}`); } }
function startWorker(): void { generation += 1; const id = generation; worker?.terminate(); worker = new Worker("./demo-worker.js"); ready = false; pending = false; ui.runtime.textContent = "启动中"; worker.addEventListener("message", ({ data }) => { if (id !== generation || !data) return; if (data.type === "ready") { ready = true; ui.runtime.textContent = "NARS 在线"; timeline.reset(); requestStep(); return; } if (data.type === "experience-reset") { timeline.reset(); return; } if (data.type === "experience") { if (data.event) timeline.add(data.event); return; } if (data.type === "experience-snapshot") { for (const event of data.events ?? []) timeline.add(event); if (data.stats) ui.experienceMeta.textContent = `窗口 ${data.stats.retained + data.stats.dropped} · 保留 ${data.stats.retained} · 丢弃 ${data.stats.dropped}`; return; } if (data.type === "operation") { ui.source.value = "NARS"; log(`NARS · ${data.action}`); return; } if (data.type === "step-complete") { pending = false; ui.source.value = (data.source ?? "idle").toUpperCase(); ui.narTime.value = String(data.narTime ?? "0"); ui.narTime.textContent = ui.narTime.value; telemetry.inference(Number(data.cycles ?? 10)); const action = data.action as Direction | null; if (action) applyMove(action.replace(/^\^/, "").toLowerCase() as Direction, data.source === "babble" ? "Babble" : "NARS"); else render(); if (running) nextStep = performance.now() + 1000 / 8; return; } if (data.type === "fault") { ui.runtime.textContent = "推理异常"; running = false; log(data.message ?? "Worker 异常"); } }); worker.postMessage({ type: "init", game: "nars2048", seed: game.seed, actions: ["^up", "^down", "^left", "^right"], priorRules: [] }); }
function requestStep(): void { if (!worker || !ready || pending || !running) return; pending = true; worker.postMessage({ type: "step", game: "nars2048", step: game.moves + 1, ...buildNarsInput(game), cycles: 10, babble: .12 }); }
function frame(now: number): void { telemetry.frame(now); if (running && ready && !pending && now >= nextStep) requestStep(); requestAnimationFrame(frame); }
mountIcons(); render(); startWorker(); requestAnimationFrame(frame);
ui.run.addEventListener("click", () => { running = !running; setIcon(ui.run, running ? "pause" : "play"); if (running) nextStep = performance.now(); });
ui.toggleMotion.addEventListener("click", () => { renderer.setMotion(!renderer.animations); ui.toggleMotion.setAttribute("aria-label", renderer.animations ? "关闭动效" : "开启动效"); });
ui.toggleParticles.addEventListener("click", () => { renderer.particlesEnabled = !renderer.particlesEnabled; ui.toggleParticles.setAttribute("aria-label", renderer.particlesEnabled ? "关闭方向粒子" : "开启方向粒子"); });
ui.resetBoard.addEventListener("click", () => { game = createGame(game.seed + game.round); game.round += 1; renderer.clear(); render(); log(`棋盘重开 · NARS 记忆保留 · ROUND ${game.round}`); });
ui.resetMemory.addEventListener("click", () => { game = createGame(game.seed); game.round = 1; render(); startWorker(); log("NARS 记忆重置"); });
ui.clearLog.addEventListener("click", () => ui.log.replaceChildren());
ui.exportLog.addEventListener("click", () => { const payload = { schema: "opennars-304-ts-lab/nars2048/v1", exportedAt: new Date().toISOString(), seed: game.seed, round: game.round, score: game.score, highest: game.highest, moves: game.moves, merges: game.merges, board: game.board, logs: [...ui.log.children].map((item) => item.textContent ?? "") }; const blob = new Blob([JSON.stringify(payload, null, 2)], { type: "application/json" }); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = `nars2048-${game.seed}-${game.round}.json`; link.click(); URL.revokeObjectURL(link.href); log("已导出匿名实验记录"); });
document.addEventListener("keydown", (event) => { const key: Record<string, Direction> = { ArrowUp: "up", ArrowDown: "down", ArrowLeft: "left", ArrowRight: "right" }; const direction = key[event.key]; if (direction && !pending) { event.preventDefault(); applyMove(direction, "手动"); } });
let touchX = 0, touchY = 0, touching = false; ui.board.addEventListener("touchstart", (event) => { if (event.touches.length !== 1) return; touching = true; touchX = event.touches[0].clientX; touchY = event.touches[0].clientY; }, { passive: true }); ui.board.addEventListener("touchmove", (event) => { if (touching) event.preventDefault(); }, { passive: false }); ui.board.addEventListener("touchend", (event) => { if (!touching) return; touching = false; const touch = event.changedTouches[0]; if (!touch) return; const dx = touch.clientX - touchX, dy = touch.clientY - touchY, threshold = Math.max(24, ui.board.clientWidth * .08); if (Math.max(Math.abs(dx), Math.abs(dy)) < threshold || pending) return; applyMove(Math.abs(dx) > Math.abs(dy) ? (dx > 0 ? "right" : "left") : dy > 0 ? "down" : "up", "手动"); }, { passive: true });
window.addEventListener("pagehide", () => { worker?.terminate(); timeline.dispose(); telemetry.dispose(); }, { once: true });
