import { modeById, PONG_MODES, createPongWorld, senseFor, applyPongActions, type PongModeId, type PongRole, type PongWorld, type PongDirection } from "./pong-lab-model.ts";
import { mountIcons, setIcon } from "./ui/icons.ts";
import { mountExperienceTimeline } from "./ui/experience-timeline.ts";
import { RuntimeTelemetryView } from "./ui/runtime-telemetry.ts";
import type { ExperienceEvent } from "./experience/contract.ts";

const el = <T extends Element>(selector: string): T => { const value = document.querySelector(selector); if (!value) throw new Error(`Missing Pong element: ${selector}`); return value as T; };
const ui = { canvas: el<HTMLCanvasElement>("#pong-canvas"), runtime: el<HTMLElement>("#pong-runtime"), title: el<HTMLElement>("#pong-title"), description: el<HTMLElement>("#pong-description"), mode: el<HTMLSelectElement>("#pong-mode"), modeLabel: el<HTMLElement>("#pong-mode-label"), roleLabel: el<HTMLElement>("#pong-role-label"), agentCount: el<HTMLOutputElement>("#pong-agent-count"), agents: el<HTMLElement>("#pong-agents"), tick: el<HTMLOutputElement>("#pong-world-tick"), topHit: el<HTMLElement>("#pong-top-hit"), topMiss: el<HTMLElement>("#pong-top-miss"), bottomHit: el<HTMLElement>("#pong-bottom-hit"), bottomMiss: el<HTMLElement>("#pong-bottom-miss"), run: el<HTMLButtonElement>("#pong-run"), step: el<HTMLButtonElement>("#pong-step"), resetWorld: el<HTMLButtonElement>("#pong-reset-world"), resetNars: el<HTMLButtonElement>("#pong-reset-nars"), speed: el<HTMLInputElement>("#pong-speed"), speedValue: el<HTMLOutputElement>("#pong-speed-value"), modeInputs: [...document.querySelectorAll<HTMLInputElement>('input[name="pong-mode"]')], experience: el<HTMLDetailsElement>("#pong-experience"), experienceList: el<HTMLOListElement>("#pong-experience-list"), experienceStatus: el<HTMLOutputElement>("#pong-experience-status"), experienceMeta: el<HTMLElement>("#pong-experience-meta"), log: el<HTMLOListElement>("#pong-log"), clearLog: el<HTMLButtonElement>("#pong-clear-log"), fps: el<HTMLOutputElement>("#fps-hud"), tps: el<HTMLOutputElement>("#tps-hud"), rps: el<HTMLOutputElement>("#rps-hud"), fpsBar: el<HTMLElement>("#fps-bar"), tpsBar: el<HTMLElement>("#tps-bar"), rpsBar: el<HTMLElement>("#rps-bar"), tpsTarget: el<HTMLOutputElement>("#pong-tps-target"), tpsRatio: el<HTMLOutputElement>("#pong-tps-ratio"), pageMemory: el<HTMLOutputElement>("#pong-page-memory"), concepts: el<HTMLOutputElement>("#pong-concepts"), taskBags: el<HTMLOutputElement>("#pong-task-bags") };
const telemetry = new RuntimeTelemetryView({ fps: ui.fps, tps: ui.tps, rps: ui.rps, tpsTarget: ui.tpsTarget, tpsRatio: ui.tpsRatio, fpsBar: ui.fpsBar, tpsBar: ui.tpsBar, rpsBar: ui.rpsBar, pageMemory: ui.pageMemory, concepts: ui.concepts, taskBags: ui.taskBags }); telemetry.setTargetTps(20); telemetry.setCyclesPerTick(10);
const context = ui.canvas.getContext("2d") as CanvasRenderingContext2D; if (!context) throw new Error("Pong canvas unavailable");
let mode = modeById("classic"), world: PongWorld = createPongWorld(), running = true, sync = true, speed = 20, nextStep = 0, generation = 0, experienceId = 0;
const agents = new Map<PongRole, { worker: Worker; pending: boolean; ready: boolean; action: PongDirection | null; source: string }>();
const timeline = mountExperienceTimeline({ details: ui.experience, list: ui.experienceList, status: ui.experienceStatus, meta: ui.experienceMeta }, (open) => agents.forEach(({ worker }) => worker.postMessage({ type: "experience-snapshot", open })));
const log = (text: string): void => { const item = document.createElement("li"); item.textContent = `${String(world.tick).padStart(5, "0")} ${text}`; ui.log.append(item); while (ui.log.children.length > 160) ui.log.firstElementChild?.remove(); ui.log.scrollTop = ui.log.scrollHeight; };
const roleLabel = (role: PongRole): string => role === "paddle" ? "挡板" : role === "ball" ? "球" : role === "top" ? "上挡板" : role === "bottom" ? "下挡板" : role === "left" ? "左控制" : "右控制";
function render(): void { const width = ui.canvas.clientWidth || 1000, height = width * .52; const ratio = window.devicePixelRatio || 1; ui.canvas.width = Math.round(width * ratio); ui.canvas.height = Math.round(height * ratio); context.setTransform(ui.canvas.width / 50, 0, 0, ui.canvas.height / 20, 0, 0); context.fillStyle = "#101713"; context.fillRect(0, 0, 50, 20); context.strokeStyle = "#304336"; context.setLineDash([.5, .7]); context.beginPath(); context.moveTo(25, 0); context.lineTo(25, 20); context.stroke(); context.setLineDash([]); for (const point of world.trail) { context.fillStyle = "rgba(115,216,199,.18)"; context.fillRect(point.x - .3, point.y - .3, .6, .6); } context.fillStyle = "#ffc56c"; context.beginPath(); context.arc(world.ball.x, world.ball.y, .48, 0, Math.PI * 2); context.fill(); context.fillStyle = "#b7e66e"; context.fillRect(world.paddles.top - 4, .55, 8, .65); context.fillStyle = "#73d8c7"; context.fillRect(world.paddles.bottom - 4, 18.8, 8, .65); if (world.flash) { context.strokeStyle = world.flash === "hit" ? "#b7e66e" : "#ff7661"; context.lineWidth = .22; context.strokeRect(.5, .5, 49, 19); } ui.tick.value = String(world.tick).padStart(6, "0"); ui.tick.textContent = ui.tick.value; ui.topHit.textContent = String(world.hits.top); ui.topMiss.textContent = String(world.misses.top); ui.bottomHit.textContent = String(world.hits.bottom); ui.bottomMiss.textContent = String(world.misses.bottom); }
function renderAgents(): void { ui.agents.replaceChildren(); for (const [role, agent] of agents) { const row = document.createElement("div"); row.className = "pong-agent"; row.dataset.status = agent.source; row.innerHTML = `<span>${roleLabel(role)}</span><strong>${agent.source} · ${agent.action ?? "IDLE"}</strong>`; ui.agents.append(row); } }
function rulesFor(_role: PongRole): string[] { const belief = (sense: string) => `<{SELF} --> [ball_${sense}]>`; const action = (name: string) => `(^${name},{SELF})`; const rules = [`<(&/,${belief("left")},${action("Left")}) =/> <{SELF} --> [good]>>.`, `<(&/,${belief("right")},${action("Right")}) =/> <{SELF} --> [good]>>.`]; if (mode.sensor === "lcr" || mode.sensor === "diff") rules.push(`<(&/,${belief("center")},${action("Idle")}) =/> <{SELF} --> [good]>>.`); return rules; }
function stepInput(role: PongRole): { beliefs: string[]; goals: string[]; feedback: string[]; cycles: number } { const senses = senseFor(world, mode, role); return { beliefs: senses.map((sense) => `<{SELF} --> [${sense}]>. :|:`), goals: ["<{SELF} --> [good]>! :|:"], feedback: world.flash === "hit" ? ["<{SELF} --> [good]>. :|:"] : [], cycles: mode.cycles }; }
function requestSteps(): void { for (const [role, agent] of agents) { if (agent.pending || !agent.ready) continue; agent.pending = true; const input = stepInput(role); agent.worker.postMessage({ type: "step", game: `pong-${mode.id}-${role}`, step: world.tick + 1, ...input, cycles: mode.cycles, babble: .08 }); } }
function applyActions(): void { const actions = new Map<PongRole, PongDirection>(); agents.forEach((agent, role) => { if (agent.action) actions.set(role, agent.action); }); const result = applyPongActions(world, actions, mode); telemetry.environmentTick(performance.now()); result.notes.forEach(log); render(); renderAgents(); }
function allSettled(): boolean { return [...agents.values()].every((agent) => !agent.pending); }
function normalizePongAction(raw: string): PongDirection { const action = raw.replace(/^\^/, "").toLowerCase(); return action === "idle" ? "stop" : action as PongDirection; }
function startWorkers(): void { generation += 1; const current = generation; agents.forEach(({ worker }) => worker.terminate()); agents.clear(); timeline.reset(); telemetry.resetRates(); ui.runtime.textContent = "启动中"; for (const role of mode.roles) { const worker = new Worker("./demo-worker.js"); const agent = { worker, pending: false, ready: false, action: null as PongDirection | null, source: "WAITING" }; agents.set(role, agent); worker.addEventListener("message", ({ data }) => { if (current !== generation || !data) return; if (data.type === "ready") { agent.ready = true; ui.runtime.textContent = "NARS 在线"; if ([...agents.values()].every((value) => value.ready)) requestSteps(); return; } if (data.type === "experience") { if (data.event) timeline.add({ ...data.event, id: ++experienceId }); return; } if (data.type === "experience-reset") return; if (data.type === "operation") { agent.action = normalizePongAction(String(data.action ?? "")); agent.source = "NARS"; return; } if (data.type === "step-complete") { agent.pending = false; agent.action = data.action ? normalizePongAction(String(data.action)) : null; agent.source = data.source === "babble" ? "BABBLE" : data.source === "NARS" ? "NARS" : "IDLE"; telemetry.inference(Number(data.cycles ?? mode.cycles)); if (sync && allSettled()) { applyActions(); if (running) nextStep = performance.now() + 1000 / speed; } else if (!sync && allSettled()) requestSteps(); renderAgents(); } }); worker.postMessage({ type: "init", game: `pong-${mode.id}-${role}`, seed: 3040304, actions: mode.actions, priorRules: rulesFor(role) }); } renderAgents(); }
function setMode(id: PongModeId): void { mode = modeById(id); ui.title.textContent = mode.title; ui.description.textContent = mode.description; ui.modeLabel.textContent = mode.title; ui.roleLabel.textContent = mode.roles.map(roleLabel).join(" + "); ui.agentCount.value = `${mode.roles.length} NARS`; ui.agentCount.textContent = ui.agentCount.value; world = createPongWorld(); startWorkers(); render(); }
function frame(now: number): void { telemetry.frame(now); if (running && sync && now >= nextStep && allSettled()) requestSteps(); if (running && !sync && now >= nextStep) { applyActions(); nextStep = now + 1000 / speed; } render(); requestAnimationFrame(frame); }
for (const option of PONG_MODES) { const item = document.createElement("option"); item.value = option.id; item.textContent = option.title; ui.mode.append(item); }
mountIcons(); ui.mode.addEventListener("change", () => setMode(ui.mode.value as PongModeId)); ui.modeInputs.forEach((input) => input.addEventListener("change", () => { if (!input.checked) return; sync = input.value === "sync"; nextStep = performance.now(); log(`节奏 · ${sync ? "同步" : "异步"}`); })); ui.speed.addEventListener("input", () => { speed = Number(ui.speed.value); ui.speedValue.value = `${speed} TPS`; ui.speedValue.textContent = ui.speedValue.value; telemetry.setTargetTps(speed); }); ui.run.addEventListener("click", () => { running = !running; setIcon(ui.run, running ? "pause" : "play"); }); ui.step.addEventListener("click", () => { running = false; requestSteps(); }); ui.resetWorld.addEventListener("click", () => { world = createPongWorld(); render(); log("世界重置 · Worker 记忆保留"); }); ui.resetNars.addEventListener("click", () => { world = createPongWorld(); startWorkers(); log("全部 NARS Worker 重置"); }); ui.clearLog.addEventListener("click", () => ui.log.replaceChildren()); setMode("classic"); requestAnimationFrame(frame); window.addEventListener("pagehide", () => { agents.forEach(({ worker }) => worker.terminate()); timeline.dispose(); telemetry.dispose(); }, { once: true });
