import { applyShotAction, buildShotNarsStep, createShotWorld, modeById, SHOT_MODES, stepShotWorld, type ShotModeId, type ShotPlayer, type ShotWorld } from "./shot-lab-model.ts";
import { mountIcons, setIcon } from "./ui/icons.ts";
import { mountExperienceTimeline } from "./ui/experience-timeline.ts";
import { RuntimeTelemetryView } from "./ui/runtime-telemetry.ts";

const el = <T extends Element>(selector: string): T => { const value = document.querySelector(selector); if (!value) throw new Error(`Missing Shot element: ${selector}`); return value as T; };
const ui = { canvas: el<HTMLCanvasElement>("#shot-canvas"), runtime: el<HTMLElement>("#shot-runtime"), title: el<HTMLElement>("#shot-title"), description: el<HTMLElement>("#shot-description"), mode: el<HTMLSelectElement>("#shot-mode"), modeLabel: el<HTMLElement>("#shot-mode-label"), roleLabel: el<HTMLElement>("#shot-role-label"), playerCount: el<HTMLOutputElement>("#shot-player-count"), agents: el<HTMLElement>("#shot-agents"), tick: el<HTMLOutputElement>("#shot-world-tick"), hits: el<HTMLElement>("#shot-hits"), misses: el<HTMLElement>("#shot-misses"), evolutions: el<HTMLElement>("#shot-evolutions"), run: el<HTMLButtonElement>("#shot-run"), step: el<HTMLButtonElement>("#shot-step"), resetWorld: el<HTMLButtonElement>("#shot-reset-world"), resetNars: el<HTMLButtonElement>("#shot-reset-nars"), speed: el<HTMLInputElement>("#shot-speed"), speedValue: el<HTMLOutputElement>("#shot-speed-value"), experience: el<HTMLDetailsElement>("#shot-experience"), experienceList: el<HTMLOListElement>("#shot-experience-list"), experienceStatus: el<HTMLOutputElement>("#shot-experience-status"), experienceMeta: el<HTMLElement>("#shot-experience-meta"), log: el<HTMLOListElement>("#shot-log"), clearLog: el<HTMLButtonElement>("#shot-clear-log"), fps: el<HTMLOutputElement>("#fps-hud"), tps: el<HTMLOutputElement>("#tps-hud"), rps: el<HTMLOutputElement>("#rps-hud"), fpsBar: el<HTMLElement>("#fps-bar"), tpsBar: el<HTMLElement>("#tps-bar"), rpsBar: el<HTMLElement>("#rps-bar"), tpsTarget: el<HTMLOutputElement>("#shot-tps-target"), tpsRatio: el<HTMLOutputElement>("#shot-tps-ratio"), pageMemory: el<HTMLOutputElement>("#shot-page-memory"), concepts: el<HTMLOutputElement>("#shot-concepts"), taskBags: el<HTMLOutputElement>("#shot-task-bags") };
const context = ui.canvas.getContext("2d") as CanvasRenderingContext2D; if (!context) throw new Error("Shot canvas unavailable");
const telemetry = new RuntimeTelemetryView({ fps: ui.fps, tps: ui.tps, rps: ui.rps, tpsTarget: ui.tpsTarget, tpsRatio: ui.tpsRatio, fpsBar: ui.fpsBar, tpsBar: ui.tpsBar, rpsBar: ui.rpsBar, pageMemory: ui.pageMemory, concepts: ui.concepts, taskBags: ui.taskBags }); telemetry.setTargetTps(20); telemetry.setCyclesPerTick(10);
type Agent = { worker: Worker; pending: boolean; ready: boolean; action: string | null; source: string; playerId: string };
let mode = modeById("shot-test"); let world: ShotWorld = createShotWorld(mode.id); let running = true; let sync = true; let speed = 20; let nextStep = 0; let generation = 0; let eventId = 0;
const workers = new Map<string, Agent>(); const queued = new Map<string, string>();
const timeline = mountExperienceTimeline({ details: ui.experience, list: ui.experienceList, status: ui.experienceStatus, meta: ui.experienceMeta }, (open) => workers.forEach(({ worker }) => worker.postMessage({ type: "experience-snapshot", open })));
const log = (text: string): void => { const item = document.createElement("li"); item.textContent = `${String(world.tick).padStart(5, "0")} ${text}`; ui.log.append(item); while (ui.log.children.length > 180) ui.log.firstElementChild?.remove(); ui.log.scrollTop = ui.log.scrollHeight; };
const playerColor = (player: ShotPlayer): string => player.ai === "nar2" ? "#68e0dd" : player.ai === "null" ? "#8ca3a5" : player.id.startsWith("clone") ? "#ffc66d" : "#c6f36b";
const directionGlyph: Record<ShotPlayer["direction"], string> = { north: "^", east: ">", south: "v", west: "<" };
const normalizeAction = (raw: string | null): string => String(raw ?? "").replace(/^\^/, "").toLowerCase();
function resizeCanvas(): void { const width = ui.canvas.clientWidth || 1000; const ratio = Math.min(window.devicePixelRatio || 1, 2); ui.canvas.width = Math.round(width * ratio); ui.canvas.height = Math.round(width * .4 * ratio); context.setTransform(ui.canvas.width / 50, 0, 0, ui.canvas.height / 20, 0, 0); }
function render(): void { resizeCanvas(); context.fillStyle = "#10191c"; context.fillRect(0, 0, 50, 20); context.strokeStyle = "rgba(104,224,221,.08)"; context.lineWidth = .04; for (let x = 0; x <= 50; x += 1) { context.beginPath(); context.moveTo(x, 0); context.lineTo(x, 20); context.stroke(); } for (let y = 0; y <= 20; y += 1) { context.beginPath(); context.moveTo(0, y); context.lineTo(50, y); context.stroke(); } for (const ray of world.rays) { const [vx, vy] = ray.direction === "north" ? [0, -1] : ray.direction === "east" ? [1, 0] : ray.direction === "south" ? [0, 1] : [-1, 0]; context.strokeStyle = ray.hit ? "#ffc66d" : "#ff7568"; context.globalAlpha = Math.min(1, ray.ttl / 3); context.lineWidth = .24; context.beginPath(); context.moveTo(ray.x + .5, ray.y + .5); context.lineTo(ray.x + .5 + vx * 5, ray.y + .5 + vy * 5); context.stroke(); context.globalAlpha = 1; } for (const player of world.players) { if (!player.alive) continue; context.fillStyle = playerColor(player); context.shadowColor = playerColor(player); context.shadowBlur = .7; context.font = "700 1.25px IBM Plex Mono, monospace"; context.textAlign = "center"; context.textBaseline = "middle"; context.fillText(directionGlyph[player.direction], player.x + .5, player.y + .5); context.shadowBlur = 0; } ui.tick.value = String(world.tick).padStart(6, "0"); ui.tick.textContent = ui.tick.value; const active = world.players.filter((player) => player.ai !== "null"); ui.playerCount.value = `${active.length} NARS`; ui.playerCount.textContent = ui.playerCount.value; ui.hits.textContent = String(active.reduce((sum, player) => sum + player.hits, 0)); ui.misses.textContent = String(active.reduce((sum, player) => sum + player.misses, 0)); ui.evolutions.textContent = String(world.evolutionEvents); }
function renderAgents(): void { ui.agents.replaceChildren(); for (const player of world.players.filter((item) => item.ai !== "null")) { const agent = workers.get(player.id); const row = document.createElement("div"); row.className = "shot-agent"; row.dataset.status = agent?.source ?? "WAITING"; row.innerHTML = `<span>${player.name} · ${player.ai}</span><strong>${agent?.source ?? "WAITING"} · ${agent?.action ?? "IDLE"}</strong>`; ui.agents.append(row); } }
function rulesFor(): string[] { const rules = [`<(&/,<{SELF} --> [target_ahead]>,(^shoot,{SELF})) =/> <{SELF} --> [hit]>>.`]; if (mode.movement === "absolute") { rules.push(`<(&/,<{SELF} --> [target_left]>,(^left,{SELF})) =/> <{SELF} --> [hit]>>.`); rules.push(`<(&/,<{SELF} --> [target_right]>,(^right,{SELF})) =/> <{SELF} --> [hit]>>.`); } else { rules.push(`<(&/,<{SELF} --> [target_left]>,(^turn_left,{SELF})) =/> <{SELF} --> [hit]>>.`); rules.push(`<(&/,<{SELF} --> [target_right]>,(^turn_right,{SELF})) =/> <{SELF} --> [hit]>>.`); } return rules; }
function requestSteps(): void { for (const [id, agent] of workers) { if (agent.pending || !agent.ready) continue; const input = buildShotNarsStep(world, id); agent.pending = true; agent.worker.postMessage({ type: "step", game: `shot-${mode.id}-${id}`, step: world.tick + 1, ...input, cycles: mode.cycles, babble: .08 }); } }
function applyActions(): void { for (const [id, action] of queued) { const notes = applyShotAction(world, id, action); notes.forEach((note) => log(`${id} · ${note}`)); } queued.clear(); const result = stepShotWorld(world); result.notes.forEach((note) => log(note)); if (result.evolved) ensureEvolutionWorkers(); telemetry.environmentTick(performance.now()); render(); renderAgents(); }
function ensureEvolutionWorkers(): void { const current = generation; for (const player of world.players.filter((item) => item.ai !== "null")) { if (workers.has(player.id)) continue; const worker = new Worker("./demo-worker.js"); const agent: Agent = { worker, pending: false, ready: false, action: null, source: "CLONING", playerId: player.id }; workers.set(player.id, agent); worker.addEventListener("message", ({ data }) => { if (current !== generation || !data) return; if (data.type === "ready") { agent.ready = true; if ([...workers.values()].every((value) => value.ready)) requestSteps(); return; } if (data.type === "experience" && data.event) { timeline.add({ ...data.event, id: ++eventId }); return; } if (data.type === "operation") { agent.action = data.action; agent.source = "NARS"; return; } if (data.type === "step-complete") { agent.pending = false; agent.action = data.action; agent.source = data.source === "babble" ? "BABBLE" : data.source === "NARS" ? "NARS" : "IDLE"; telemetry.inference(Number(data.cycles ?? mode.cycles)); if (data.action) queued.set(player.id, normalizeAction(data.action)); if (sync && [...workers.values()].every((value) => !value.pending)) applyActions(); renderAgents(); } if (data.type === "fault") { agent.source = "FAULT"; log(`${player.id} · ${data.message ?? "Worker 异常"}`); } }); worker.postMessage({ type: "init", game: `shot-${mode.id}-${player.id}`, seed: world.seed + player.id.length, actions: mode.movement === "absolute" ? ["^up", "^down", "^left", "^right", "^shoot"] : ["^forward", "^turn_left", "^turn_right", "^shoot"], priorRules: rulesFor() }); log(`进化 · 新环境角色 ${player.name} 使用新 Worker，NARS 记忆未复制`); } }
function startWorkers(): void { generation += 1; const current = generation; workers.forEach(({ worker }) => worker.terminate()); workers.clear(); queued.clear(); timeline.reset(); telemetry.resetRates(); ui.runtime.textContent = "启动中"; for (const player of world.players.filter((item) => item.ai !== "null")) { const worker = new Worker("./demo-worker.js"); const agent: Agent = { worker, pending: false, ready: false, action: null, source: "WAITING", playerId: player.id }; workers.set(player.id, agent); worker.addEventListener("message", ({ data }) => { if (current !== generation || !data) return; if (data.type === "ready") { agent.ready = true; ui.runtime.textContent = "NARS 在线"; if ([...workers.values()].every((value) => value.ready)) requestSteps(); return; } if (data.type === "experience" && data.event) { timeline.add({ ...data.event, id: ++eventId }); return; } if (data.type === "operation") { agent.action = data.action; agent.source = "NARS"; return; } if (data.type === "step-complete") { agent.pending = false; agent.action = data.action; agent.source = data.source === "babble" ? "BABBLE" : data.source === "NARS" ? "NARS" : "IDLE"; telemetry.inference(Number(data.cycles ?? mode.cycles)); if (data.action) queued.set(player.id, normalizeAction(data.action)); if (sync && [...workers.values()].every((value) => !value.pending)) { applyActions(); if (running) nextStep = performance.now() + 1000 / speed; } renderAgents(); } if (data.type === "fault") { agent.source = "FAULT"; ui.runtime.textContent = "推理异常"; log(`${player.id} · ${data.message ?? "Worker 异常"}`); } }); worker.postMessage({ type: "init", game: `shot-${mode.id}-${player.id}`, seed: world.seed + player.id.length, actions: mode.movement === "absolute" ? ["^up", "^down", "^left", "^right", "^shoot"] : ["^forward", "^turn_left", "^turn_right", "^shoot"], priorRules: rulesFor() }); } renderAgents(); }
function setMode(id: ShotModeId): void { mode = modeById(id); world = createShotWorld(id); ui.title.textContent = "NARS Shot"; ui.description.textContent = mode.subtitle; ui.modeLabel.textContent = mode.title; ui.roleLabel.textContent = `50 × 20 · ${mode.movement === "absolute" ? "绝对移动" : "相对移动"} · 环境角色克隆不复制 NARS 记忆`; startWorkers(); render(); }
function frame(now: number): void { telemetry.frame(now); if (running && sync && now >= nextStep && [...workers.values()].every((agent) => !agent.pending)) requestSteps(); if (running && !sync && now >= nextStep) { applyActions(); nextStep = now + 1000 / speed; } render(); requestAnimationFrame(frame); }
for (const option of SHOT_MODES) { const item = document.createElement("option"); item.value = option.id; item.textContent = option.title; ui.mode.append(item); }
mountIcons(); ui.mode.addEventListener("change", () => setMode(ui.mode.value as ShotModeId)); document.querySelectorAll<HTMLInputElement>('input[name="shot-mode"]').forEach((input) => input.addEventListener("change", () => { if (!input.checked) return; sync = input.value === "sync"; nextStep = performance.now(); log(`节奏 · ${sync ? "同步" : "异步"}`); })); ui.speed.addEventListener("input", () => { speed = Number(ui.speed.value); ui.speedValue.value = `${speed} TPS`; ui.speedValue.textContent = ui.speedValue.value; telemetry.setTargetTps(speed); }); ui.run.addEventListener("click", () => { running = !running; setIcon(ui.run, running ? "pause" : "play"); }); ui.step.addEventListener("click", () => { running = false; requestSteps(); }); ui.resetWorld.addEventListener("click", () => { world = createShotWorld(mode.id); render(); log("世界重置 · Worker 记忆保留"); }); ui.resetNars.addEventListener("click", () => { world = createShotWorld(mode.id); startWorkers(); log("全部 NARS Worker 重置"); }); ui.clearLog.addEventListener("click", () => ui.log.replaceChildren()); setMode("shot-test"); requestAnimationFrame(frame); window.addEventListener("pagehide", () => { workers.forEach(({ worker }) => worker.terminate()); timeline.dispose(); telemetry.dispose(); }, { once: true });
